### ISSUE TITLE
1.8 CK에디터 모바일에서 동작이 되지 않습니다.

### ISSUE THREAD

**Issue by wookho** [xpressengine/xe-core#1384]
상단의 기능의 담당하는 메뉴들과 아이콘들 전부 노출되지 않으며 내용입력란도 활성화가 되지 않습니다.
테스트 환경은 스케치북5의 PC용 스킨을 모바일에서 PC보기로 하여 CK에디터를 적용해서 모바일에서 테스트 하였습니다.

**Comment by bnu** [comment]
해당 증상이 재현되지 않습니다.
확인할 수 있는 URL을 알려주시거나, 해당 페이지에서 스크립트 오류가 발생하고 있지 않은지 확인해주세요.
(비공개 메시지를 원할경우 developers@xpressengine.com 으로 연락주세요)

**Comment by wookho** [comment]
@bnu 이문제는 모바일로 접속을 해보셔야 확인이 가능할 것으로 보이구요. 단말기에 따라 특성을 탈 수있다고 봅니다. 제가 공홈에 모바일테스트 환경을 좀 열어달라고 부탁을 했었는데 테스트여건이 주어지지 않았습니다. 제 기억으로는 공홈의 ck테스트 게시판도 모바일에서 pc보기로 하였을때 동일한 문제가 있었습니다. 지금은 해결이 되었는지 다시 테스트 해보야 겠네요. 제 휴대폰은 안드로이드계열입니다.

**Comment by wookho** [comment]
@bnu 요청하신 url https://www.xpressengine.com/cktest  입니다.
여기를 모바일보기로 하셔서 에디터 화면을 확인해 보세요..
![2015-04-09 03 48 33](https://cloud.githubusercontent.com/assets/6590236/7060158/ff56c298-deb6-11e4-920a-3cc3069e741a.png)

**Comment by bnu** [comment]
@wookho iOS 기기에서 확인하여 문제 없었으나, 안드로이드 기기에서 문제 확인했습니다.

**Comment by YJSoft** [comment]
CKEditor supports mobile versions of Safari (default browser on iPhone and iPad) and Chrome (available for Android and preinstalled on many Android devices) with minor issues related to platform limitations.

CKEditor is currently disabled on other browsers available for Android devices due to irreparable compatibility issues.

CKEditor에서는 모바일 사파리 브라우저와 모바일 크롬을 제외한 기타 안드로이드 브라우저를 지원하지 않습니다. CKEDITOR.env.isCompatible 값을 true로 바꿈으로(CKEditor 인스턴스 초기화전 넣어야 합니다) 사용 가능하게 할 수 있으나 호환성 문제 등이 발생할 수 있습니다.

**Comment by wookho** [comment]
@YJSoft 그럼 최조 모바일에서도 첨부기능이 가능하고 활용이 가능해서 채용했다던 취지는 어떻게 되는건가요 ? 1.8에서 모바일쪽의 에디터적용과 그로 인한 파일업로드에 관련하여 기다리는 개발자와 사용자들이 있을텐데요.

안드로이드 브라우저를 지원하지 않는다..........
안드로이드를 배제한 에디터 선택이었던 것인가요 ?

**Comment by YJSoft** [comment]
@wookho #1389 대로 수정해 보시고 되는지 여부를 알려주세요.

**Comment by wookho** [comment]
@YJSoft 네. 말씀하신 대로 수정 후 정상적으로 에디터 사용이 가능해 짐을 확인했습니다.

**Comment by bnu** [comment]
fixed #1389
