### ISSUE TITLE
Cannot update XE 1.8.20 to 1.8.29

### ISSUE THREAD

**Issue by Salapao007** [xpressengine/xe-core#2013]
I want to update my XE 1.8.20 to 1.8.29
I update XE Core by click UPDATE button at EasyInstall section.
Then it shows me the message "Successfully Installed". But my current version still 1.8.20 

Can you help to update my XE Core to the latest version?
Thank you in advance.

**Comment by clamo** [comment]
There are a handful of bugs related to XE Core upgrade.

What you can do is to overwrite the latest XE Core files. The easiest way would be to correctly archive a zip file, upload it then extract it on the server. Uploading through FTP by each file may introduce a new bug due to possible corrupted file transfer.

Before doing so, always remember to make a backup. Unfortunately, XE Core upgrade is such a dangerous game to play, so always expect things to break.
